# Generated by Django 5.0.6 on 2024-06-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "path",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("original_url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("visits", models.PositiveIntegerField(default=0)),
                ("created_ip", models.CharField(default="Unknown", max_length=200)),
                (
                    "created_location",
                    models.CharField(default="Unknown", max_length=200),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
